version: "3.8"
volumes:
  nginx-conf:
  nginx-certs:
  nginx-vhost:
  nginx-public:

networks:
  default:
  reverseproxy:
    external: true
    name: reverseproxy

services:
  nginx:
    image: nginx
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.reverseproxy==true"
    labels:
      - reverseproxy.nginx
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-public:/usr/share/nginx/html
    networks:
      - reverseproxy
    ports:
      - 80:80
      - 443:443
  nginx-gen:
    image: duvalhub/nginx-companion
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.reverseproxy==true"
    environment:
      - WAIT_TIME=300
      - DEVELOPMENT=false
      # - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      - DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nginx-conf:/etc/nginx/conf.d
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-public:/usr/share/nginx/html


 