version: "3.8"
volumes:
  nginx-conf:
  nginx-certs:

networks:
  default:
  reverseproxy:
    external: true
    name: reverseproxy

services:
  nginx:
    image: nginx
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.reverseproxy==true"
    labels:
      - reverseproxy.nginx_proxy
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-certs:/etc/nginx/certs
    networks:
      - reverseproxy
    environment:
      - DEBUG=true
    ports:
      - 80:80
      - 443:443
  nginx-gen:
    image: docker-gen-services
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.reverseproxy==true"
    # networks:
      # - reverseproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nginx-conf:/etc/nginx/conf.d
      - nginx-certs:/etc/nginx/certs

 