version: "3.8"

networks:
  reverseproxy:
    external: true
    name: reverseproxy

services:
  test-app:
    image: nginxdemos/hello
    deploy:
      replicas: 2
      labels:
        reverseproxy.host: "toto.vps287088.duvalhub.com"
        # reverseproxy.ssl: "true"
    networks:
      - reverseproxy
  # test-app2:
  #   image: nginxdemos/hello
  #   deploy:
  #     replicas: 2
  #     labels:
  #       reverseproxy.host: "toto2.vps287088.duvalhub.com"
  #       reverseproxy.ssl: "true"
  #   networks:
  #     - reverseproxy     
  # test-app3:
  #   image: nginxdemos/hello
  #   deploy:
  #     replicas: 2
  #     labels:
  #       reverseproxy.host: "toto3.vps287088.duvalhub.com"
  #       reverseproxy.ssl: "true"
  #   networks:
  #     - reverseproxy
  # test-app4:
  #   image: nginxdemos/hello
  #   deploy:
  #     replicas: 2
  #     labels:
  #       reverseproxy.host: "toto4.vps287088.duvalhub.com"
  #       # reverseproxy.ssl: "true"
  #   networks:
  #     - reverseproxy
#  test-app5:
#     image: nginxdemos/hello
#     deploy:
#       replicas: 2
#     environment:
#       - VIRTUAL_HOST=toto5.vps287088.duvalhub.com
#       - LETSENCRYPT_HOST=toto5.vps287088.duvalhub.com
#     networks:
#       - reverseproxy     
#  test-app-totoafrica:
#     image: nginxdemos/hello
#     deploy:
#       replicas: 2
#     environment:
#       - VIRTUAL_HOST=totoafrica.vps287088.duvalhub.com
#       - LETSENCRYPT_HOST=totoafrica.vps287088.duvalhub.com
#     networks:
#       - reverseproxy     
