version: "3.8"
volumes:
  nginx-conf:
  nginx-certs:
  nginx-vhost:
  nginx-public:

networks:
  default:
  reverseproxy:
    external: true
    name: reverseproxy

services:
  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.reverseproxy==true"
    labels:
      - reverseproxy.nginx
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-public:/usr/share/nginx/html
    networks:
      - reverseproxy
    ports:
      - 80:80
      - 443:443
  nginx-companion:
    image: duvalhub/nginx-companion
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.reverseproxy==true"
    environment:
      - MODE=${MODE}
      - DEBUG=${DEBUG}
      - DEFAULT_EMAIL=${EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nginx-conf:/etc/nginx/conf.d
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-public:/usr/share/nginx/html
